### ISSUE TITLE
Abrir Proyecto 2

### ISSUE THREAD

**Issue by TheKillerNormie** [RakuTheSenpai/pixel_art#3]
Título
Duración
Prioridad
Abrir proyecto 2

Media
Como: Carlos Creativo
Quiero: que la cuadrícula de mi “dashboard” se actualice con el progreso del archivo seleccionado
Para: observar el progreso que tenía

Criterios de Aceptación: Tras seleccionar el archivo del proyecto deseado, la cuadrícula debe reflejar los últimos cambios guardados por Carlos en el proyecto.

Tareas:
1. Crear funcionalidad para abrir un proyecto con la informacion almacenada en el archivo .pxart seleccionado.

**Comment by KillerFarmer** [comment]
Como: Carlos Creativo
Quiero: que la cuadrícula de mi “dashboard” se actualice con el progreso del archivo seleccionado
Para: observar el progreso que tenía

Criterios de Aceptación: Tras seleccionar el archivo del proyecto deseado, la cuadrícula debe reflejar los últimos cambios guardados por Carlos en el proyecto.

Tareas:
Crear funcionalidad para abrir un proyecto con la informacion almacenada en el archivo .pxart seleccionado.
